version: '2.4'

services:
  brunch:
    build:
      context: ./
      dockerfile: docker/brunch.dockerfile
    restart: always
    ports:
      - "3333:3333"
      - "9485:9485"
    volumes:
      - ./client/:/app
      - ./docs/:/app/docs
